hosts.yaml
all:
  hosts:
    my_servers:
      ansible_host: 192.168.130.148
      ansible_user: stephenhwan
      ansible_ssh_pass: 1234
      ansible_become: yes
      ansible_become_method: sudo
      ansible_become_password: 1234
      ansible_pkg_mgr: apt